name: "Hello World Message"
on:
  push:
jobs:
  hello_world:
      name: "Hello World"
      runs-on: ubuntu-latest
      steps:
        - name: "Hello World"
          run : |
              echo "Hello World !"

  pylint:
      name: "Check Linter"
      runs-on: ubuntu-latest
      steps:
        - run: python --version