name: "Hello World Message"
on:
  push:
jobs:
  hello_world:
      name: "Hello World"
      runs-on: ubuntu-latest
      steps:
        - name: "Hello World"
          run : |
              echo "Hello World !"

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install pylint
      - run: pylint ./main.py

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install pytest
      - run: pytest ./main.py