name: "Hello World Message"
on:
  push:
jobs:
  hello_world:
      name: "Hello World"
      runs-on: ubuntu-latest
      steps:
        - name: "Hello World"
          run : |
              echo "Hello World !"

  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install pylint  # -r requirements.txt
      - run: pylint **/*.py