name: "Hello World Message"
on:
  push:
jobs:
  hello world:
      name: "Hello World"
      runs-on: ubuntu-latest
      steps:
        - name: "Hello World"
          run : |
              echo "Hello World !"

  pylint:
      name: "Check Linter"
      runs-on: ubuntu-latest
      steps:
        - run: ls -l
        - run: find .
        - run: pip install pylint  # -r requirements.txt
        - run: pylint main.py